localizome/urls.py
from django.conf.urls import include, url


urlpatterns = [
    url(r'^', include('website.urls')),
]

website/urls.py
from django.conf.urls import url

from . import views


# urlpatterns is a module-level variable
urlpatterns = [
    url(r'^$', views.home,
        name='home_url'),
    url(r'^proteins/$', views.protein_list,
        name='protein_list_url'),
    url(r'^protein/(?P<common_name>.+)/$', views.protein_detail,
        name='protein_detail_url'),
    url(r'^spatiotemporal/$', views.spatiotemporal_search,
        name='spatiotemporal_search_url'),
    url((r'^spatiotemporal/compartment(?P<compartment>\d{1,2})/'
         'timepoint(?P<timepoint>\d{1,2})/$'),
        views.spatiotemporal_both, name='spatiotemporatl_both_url'),
    url(r'^spatiotemporal/compartment(?P<compartment>\d{1,2})/$',
        views.spatiotemporal_compartment,
        name='spatiotemporal_compartment_url',),
    url(r'^spatiotemporal/timepoint(?P<timepoint>\d{1,2})/$',
        views.spatiotemporal_timepoint,
        name='spatiotemporat_timepoint_url'),
    url(r'^network/$', views.network,
        name='network_url'),
    url(r'^downloads/$', views.downloads,
        name='downloads_url'),
    url(r'^downloads/(?P<common_name>.+)/$', views.downloads_protein,
        name='downloads_protein_url'),
]

website/models.py
from django.db import models


class Protein(models.Model):
    common_name = models.CharField(max_length=10, unique=True)
    sequence = models.CharField(max_length=15, unique=True)
    wormbase_id = models.CharField(max_length=15, unique=True)
    in_paper = models.BooleanField(default=True)
    representative_video = models.OneToOneField(
        'Video', related_name='representative', null=True, unique=True)
    network_x_coordinate = models.PositiveIntegerField(null=True)
    network_y_coordinate = models.PositiveIntegerField(null=True)

    def __unicode__(self):
        return self.common_name

    class Meta:
        ordering = ['common_name']
        unique_together = ('network_x_coordinate', 'network_y_coordinate')


class Strain(models.Model):
    name = models.CharField(max_length=10, blank=True)

    # genotype is vector if miyeko's strain (to dynamically generate
    # genotype), is hard-coded if not hers and not on WormBase, and
    # is blank otherwise.
    genotype = models.CharField(max_length=100, blank=True)
    protein = models.ForeignKey(Protein)
    note = models.CharField(max_length=75, blank=True)

    def __unicode__(self):
        return self.name


class Video(models.Model):
    protein = models.ForeignKey(Protein)
    strain = models.ForeignKey(Strain)
    filename = models.CharField(max_length=30, unique=True)
    movie_number = models.PositiveSmallIntegerField()
    excel_id = models.PositiveSmallIntegerField(unique=True, null=True)
    date_filmed = models.DateField()
    date_scored = models.DateField(null=True)
    lens = models.CharField(max_length=5, blank=True)
    mode = models.CharField(max_length=70, blank=True)
    summary = models.CharField(max_length=2000, blank=True)

    def __unicode__(self):
        return self.protein

    def shortened_filename(self):
        # remove protein from beginning of string
        s = self.filename.partition('_')[2]

        # remove date from end of string
        s = s.rpartition('_')[0]
        return s

    class Meta:
        ordering = ['movie_number']


class Compartment(models.Model):
    name = models.CharField(max_length=60, unique=True)

    # blank indicates to not display compart.
    short_name = models.CharField(max_length=20, blank=True)

    # when axes flip
    extra_short_name = models.CharField(max_length=5, blank=True)

    PERIPHERY_SUPERCOMPARTMENT = 1
    CYTOPLASMIC_SUPERCOMPARTMENT = 2
    NUCLEAR_SUPERCOMPARTMENT = 3

    SUPERCOMPARTMENT_CATEGORIES = (
        (PERIPHERY_SUPERCOMPARTMENT, 'Periphery/Plasma Membrane'),
        (CYTOPLASMIC_SUPERCOMPARTMENT, 'Cytoplasmic'),
        (NUCLEAR_SUPERCOMPARTMENT, 'Nuclear')
    )
    supercompartment = models.PositiveSmallIntegerField(
        choices=SUPERCOMPARTMENT_CATEGORIES)

    class Meta:
        ordering = ['id']


class Timepoint(models.Model):
    # timepoint names NOT unique (depend on cell cycle)
    name = models.CharField(max_length=30)
    short_name = models.CharField(max_length=5)

    ONE_CELL_CYCLE = 1
    AB_CELL_CYCLE = 2
    P1_CELL_CYCLE = 3

    CELL_CYCLE_CATEGORIES = (
        (ONE_CELL_CYCLE, '1-Cell'),
        (AB_CELL_CYCLE, 'AB'),
        (P1_CELL_CYCLE, 'P1')
    )
    cell_cycle_category = models.PositiveSmallIntegerField(
        choices=CELL_CYCLE_CATEGORIES)

    class Meta:
        ordering = ['id']


class Signal(models.Model):
    ABSENT_STRENGTH = 0
    UNKNOWN_STRENGTH = 1
    WEAK_STRENGTH = 2
    PRESENT_STRENGTH = 3

    STRENGTH_CATEGORIES = (
        (ABSENT_STRENGTH, 'absent'),
        (UNKNOWN_STRENGTH, 'na'),
        (WEAK_STRENGTH, 'weak'),
        (PRESENT_STRENGTH, 'present')
    )

    strength = models.PositiveSmallIntegerField(
        choices=STRENGTH_CATEGORIES, db_index=True)
    compartment = models.ForeignKey(Compartment)
    timepoint = models.ForeignKey(Timepoint)

    class Meta:
        # parent class for SignalRaw and SignalMerged
        abstract = True


class SignalRaw(Signal):
    video = models.ForeignKey(Video)

    class Meta:
        ordering = ['video', 'compartment', 'timepoint']


class SignalMerged(Signal):
    protein = models.ForeignKey(Protein)

    class Meta:
        ordering = ['protein', 'compartment', 'timepoint']

website/views.py
from django.template import RequestContext # extends Context; needed for STATIC_URL
from django.shortcuts import render_to_response, get_object_or_404 # r_to_r loads template, passes context, renders
from django.db.models import Q # enables AND and OR in SQL filters
from website.models import *

def home(request):
	"""
	Homepage
	"""
	# render page
	return render_to_response('home.html', context_instance=RequestContext(request))


def protein_list(request):
	"""
	Page listing all proteins tested
	"""
	# get all proteins
	p = Protein.objects.all()

	# render page
	return render_to_response('protein_list.html', {'proteins':p}, context_instance=RequestContext(request))


def network(request):
	"""
	Page with network image
	"""
	p = Protein.objects.filter(network_x_coordinate__isnull=False)
	
	for protein in p:
		protein.network_x_coordinate_adjusted = protein.network_x_coordinate - 30
		protein.network_y_coordinate_adjusted	= protein.network_y_coordinate - 5
	
	# render page
	return render_to_response('network.html', {
		'proteins':p,
	}, context_instance=RequestContext(request))


def protein_detail(request, common_name):
	"""
	Page for each protein, with protein's videos, matrices, and other information
	"""
	# get protein from common name, its videos
	p = get_object_or_404(Protein, common_name=common_name)
	v = Video.objects.filter(protein_id=p.id)

	# get all compartments and timepoints
	c = Compartment.objects.all()
	t = Timepoint.objects.all()
	num_timepoints = len(t)

	matrices = [] # list of matrices. Each element: [video.id or "merge"][corresponding matrix]
	
	for video in v:
		# if summary length is longer than can fit on page
		if len(video.summary) > 600:
			# add truncated summary to video
			video.truncated_summary = video.summary[:500]
		
		# for not found videos (currently just one), add a field so warning message displays
		if video.filename == "NUM1_PF1134_3_120510":
			video.lost = 1

		# get the strain corresponding to the video, and process the strain's genotype
		video.strain = get_object_or_404(Strain, id=video.strain_id) # get strain
		
		# if Miyeko's strain, generate genotype from vector and protein.
		if video.strain.genotype == 'pJon': 
			video.strain.genotype = "unc-119(ed3) III; nnIs[unc-119(+) + Ppie-1::GFP-TEV-STag::" + p.common_name + "::3'pie-1]"
		elif video.strain.genotype == 'pDESTMB16':
			video.strain.genotype = "unc-119(ed3) III; nnIs[unc-119(+) + Ppie-1::" + p.common_name + "::GFP::3'pie-1]"
		
		# if non-Miyeko-made strains missing a hard-coded genotype entry in the database, it means they can be linked to on WormBase
		if not video.strain.genotype:
			video.strain.wormbase = "http://www.wormbase.org/species/c_elegans/strain/" + video.strain.name
		
		# process signals for the video; relies on signals being sorted
		signals = SignalRaw.objects.filter(video_id=video.id) # get all signals as one list
			
		matrix = [] # list of rows for this matrix. Each element: [compartment][list of signals for that row]
		i = 0 # index for beginning of current row
		if signals:
			for compartment in c: # for each row
				matrix.append((compartment, signals[i:(i+num_timepoints)])) # add this row's compartment and signals
				i += num_timepoints # raw matrices do have these rows, so skip them
			matrices.append((video.id, matrix))
	
	# add the merge matrix to matrices
	matrix = [] # refresh matrix
	i = 0 # refresh index
	signals = SignalMerged.objects.filter(protein_id=p.id) # get all signals as one list
	if signals:
		for compartment in c: # for each row
			matrix.append((compartment, signals[i:(i+num_timepoints)])) # add this row's compartment and signals
			i += num_timepoints
		matrices.append(("merge", matrix))
	
	# render page
	return render_to_response('protein_detail.html', {
		'protein':p, 
		'videos':v,
		'timepoints':t,
		'matrices':matrices,
	}, context_instance=RequestContext(request))


def spatiotemporal_search(request):
	"""
	Page with spatiotemporal matrix showing number of proteins 
	expressed at every spatiotemporal point
	"""
	# get all compartments and timepoints
	c = Compartment.objects.all()
	t = Timepoint.objects.all()
	
	# create a 2D array of all 0s for the matrix signals	
	signal_matrix = [[0 for x in range(0, len(t)+1)] for x in range(0, len(c)+1)] 
	
	# get ALL merge signals
	signals = SignalMerged.objects.filter(Q(strength=2) | Q(strength=3))

	# iterate through signals, incrementing corresponding cell in matrix
	for signal in signals:
		signal_matrix[signal.compartment_id][signal.timepoint_id] += 1
	
	matrices = [] #2D array for matrices ["spatiotemporal"][corresponding matrix]
	matrix = [] # list of rows for this matrix. Each element: [compartment][list of signals for that row]

	for compartment in c:
		matrix.append((compartment, signal_matrix[compartment.id][1:]))

	matrices.append(("spatiotemporal", matrix))
	
	# render page
	return render_to_response('spatiotemporal_search.html', {
		'timepoints':t,
		'matrices':matrices,
	}, context_instance=RequestContext(request))


def spatiotemporal_both(request, compartment, timepoint):
	"""
	Results page for coexpressed proteins given a compartment AND timepoint
	"""
	# get this timepoint and compartment
	c = Compartment.objects.get(id=compartment)
	t = Timepoint.objects.get(id=timepoint)

	# get all proteins present or weak in this compartment at this timepoint
	s = SignalMerged.objects.filter(
		Q(compartment_id = compartment),
		Q(timepoint_id = timepoint),
		Q(strength=2) | Q(strength=3)
	)

	# render page
	return render_to_response('spatiotemporal_both.html', {
		'signals':s,
		'compartment':c,
		'timepoint':t
	}, context_instance=RequestContext(request))


def spatiotemporal_compartment(request, compartment):
	"""
	Results page for coexpressed proteins given a compartment only
	"""
	# get this compartment and ALL timepoints
	c = Compartment.objects.get(id=compartment)
	t = Timepoint.objects.all()
	
	# get all proteins present or weak at any time in this compartment 
	p = SignalMerged.objects.values('protein').filter(
		Q(compartment_id = compartment),
		Q(strength=2) | Q(strength=3)
	).distinct()

	# get ALL signals for these proteins in this compartments
	s = SignalMerged.objects.filter(
		Q(protein_id__in=p),
		Q(compartment_id = compartment)
	)

	# render page
	return render_to_response('spatiotemporal_compartment.html', {
		'signals':s,
		'compartment':c,
		'timepoints':t
	}, context_instance=RequestContext(request))

	
def spatiotemporal_timepoint(request, timepoint):
	"""
	Results page for coexpressed proteins given a timepoint only
	"""
	# get this timepoint and ALL compartments
	t = Timepoint.objects.get(id=timepoint)
	c = Compartment.objects.all()

	# get all proteins present or weak in any compartment at this timepoint
	p = SignalMerged.objects.values('protein').filter(
		Q(timepoint_id = timepoint), 
		Q(strength=2) | Q(strength=3)
	).distinct()

	# get ALL signals for these proteins at this timepoint
	s = SignalMerged.objects.filter(
		Q(protein__in=p),
		Q(timepoint_id = timepoint)
	)

	# render page
	return render_to_response('spatiotemporal_timepoint.html', {
		'signals':s,
		'timepoint':t,
		'compartments':c
	}, context_instance=RequestContext(request))

website/views/downloads_view.py
from django.shortcuts import get_object_or_404, render
from website.models import Protein, Video


def downloads(request):
    """
    Download page including downloads for a specific protein
    """
    proteins = Protein.objects.all()

    # render page
    return render(request, 'downloads.html', {'proteins': proteins})


def downloads_protein(request, common_name):
    proteins = Protein.objects.all()

    if common_name:
        p = get_object_or_404(Protein, common_name=common_name)
        v = Video.objects.filter(protein_id=p.id)

        for video in v:
            video.avi = video.filename + ".avi"
            video.mp4 = video.filename + ".mp4"
            video.ogv = video.filename + ".ogv"

    # render page
    return render(request, 'downloads.html', {
        'proteins': proteins,
        'protein': p,
        'videos': v,
    })

website/views/home_view.py
from django.shortcuts import render


def home(request):
    """
    Homepage
    """
    # render page
    return render(request, 'home.html')

website/views/network_view.py
from django.shortcuts import render
from website.models import Protein


def network(request):
    """
    Page with network image
    """
    p = Protein.objects.filter(network_x_coordinate__isnull=False)

    for protein in p:
        protein.network_x_coordinate_adjusted = protein.network_x_coordinate-30
        protein.network_y_coordinate_adjusted = protein.network_y_coordinate-5

    # render page
    return render(request, 'network.html', {'proteins': p})

website/views/protein_detail_view.py
from django.shortcuts import get_object_or_404, render
from website.models import (Compartment, Protein, SignalMerged, SignalRaw,
                            Strain, Timepoint, Video,)


def protein_detail(request, common_name):
    """
    Page for each protein, with protein's videos, matrices, and other info.
    """
    # get protein from common name in url
    p = get_object_or_404(Protein, common_name=common_name)
    v = Video.objects.filter(protein_id=p.id)
    c = Compartment.objects.all()
    t = Timepoint.objects.all()
    num_timepoints = len(t)

    for video in v:
        # if summary length is longer than can fit on page, add truncated
        if len(video.summary) > 600:
            video.truncated_summary = video.summary[:500]

        # for unavailable videos, add a field so warning message displays
        if video.filename == "NUM1_PF1134_3_120510":
            video.lost = 1

        # get the worm strain depicted in the video
        video.strain = get_object_or_404(Strain, id=video.strain_id)

        """
        From the strain, generate genotype based on these 3 cases:
        1) if strain made by Miyeko, db genotype field is simply "pJon" or
           "pDESTMB16"
        2) if strain not made by Miyeko and on WormBase, the genotype field
           is empty
        3) if strain not made by Miyeko and NOT on Wormbase, full genotype
           listed in the genotype field
        """
        if video.strain.genotype == 'pJon':
            video.strain.genotype = (
                "unc-119(ed3) III; nnIs[unc-119(+) + Ppie-1::GFP-TEV-STag::" +
                p.common_name + "::3'pie-1]")
        elif video.strain.genotype == 'pDESTMB16':
            video.strain.genotype = (
                "unc-119(ed3) III; nnIs[unc-119(+) + Ppie-1::" +
                p.common_name + "::GFP::3'pie-1]")

        if not video.strain.genotype:
            video.strain.wormbase = (
                "http://www.wormbase.org/species/c_elegans/strain/" +
                video.strain.name)

        # process signals for the video; this relies on signals being sorted
        signals = SignalRaw.objects.filter(video_id=video.id)

        if signals:
            # list of rows for this matrix.
            # Each element: [compartment][list of signals for that row]
            matrix = []
            i = 0  # index for beginning of current row
            for compartment in c:  # for each row
                # add this row's compartment and signals
                matrix.append((compartment, signals[i:(i+num_timepoints)]))

                # raw matrices do have these rows, so skip them
                i += num_timepoints
            video.matrix = matrix

    # if consensus matrix (aka merge matrix), add to protein
    signals = SignalMerged.objects.filter(protein_id=p.id)
    if signals:
        consensus_matrix = []
        i = 0
        for compartment in c:  # for each row
            # add this row's compartment and signals
            consensus_matrix.append((compartment,
                                     signals[i:(i+num_timepoints)]))
            i += num_timepoints
        p.consensus_matrix = consensus_matrix

    # render page
    return render(request, 'protein_detail.html', {
        'protein': p,
        'videos': v,
        'timepoints': t,
    })

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <!-- HEAD -->
  {% include "head.html" %}

  <body>
    <div id="wrap-header">
      <div id="header" class="clearfix">
        <!-- Site Title -->
        <a href="{% url 'home_url' %}">
          <img src="{{ STATIC_URL }}images/ee-logo.png">
        </a>
        <h1>Early Embryo Localizome</h1>

        <!-- MENU -->
        {% include "menu.html" %}
      </div>
    </div>

    <div id="wrap-content">
      <div id="content">
        <!-- PAGE TITLE.. h2 or h3 based on clear or no-clear -->
        {% block page_title %}{% endblock %}

        <!-- REST OF CONTENT -->
        {% block content %}{% endblock %}
      </div>
    </div>

    <!-- FOOTER -->
    {% include "footer.html" %}
  </body>
</html>

website/templates/footer.html
<div id="wrap-footer">
  <div id="footer">
    <div id="footer-left">
      Data:
      Miyeko Mana,
      Kahn Rhrissorrakrai,
      and
      <a href="http://biology.as.nyu.edu/object/FabioPiano.html" target="_blank">Fabio Piano</a>
      <br>
      <a href="http://cgsb.as.nyu.edu/" target="_blank">Center for Genomics and Systems Biology</a>,
      NYU,
      2007-2013
    </div>
    <div id="footer-right">
      Website:
      <a href="http://www.katherineerickson.com/" target="_blank">Katherine Erickson</a>
      <br>
      Code on <a href="https://github.com/katur/localizome" target="_blank">GitHub</a>,
      2013
    </div>
  </div>
</div>

website/templates/head.html
{% load staticfiles %}


<head>
  <link href="{% static 'images/favicon.ico' %}"
    rel="icon" type="image/x-icon" />

  <link href="{% static 'css/universal.css' %}"
    rel="stylesheet" type="text/css" />

  <link href="{% static 'css/header.css' %}"
    rel="stylesheet" type="text/css" />

  <link href="{% static 'css/footer.css' %}"
    rel="stylesheet" type="text/css" />

  <link href="{% static 'css/home.css' %}"
    rel="stylesheet" type="text/css" />

  <link href="{% static 'css/protein_list.css' %}"
    rel="stylesheet" type="text/css" />

  <link href="{% static 'css/protein_detail.css' %}"
    rel="stylesheet" type="text/css" />

  <link href="{% static 'css/spatiotemporal.css' %}"
    rel="stylesheet" type="text/css" />

  <link href="{% static 'css/network.css' %}"
    rel="stylesheet" type="text/css" />

  <link href="{% static 'css/downloads.css' %}"
    rel="stylesheet" type="text/css" />

  <link href="{% static 'css/matrix.css' %}"
    rel="stylesheet" type="text/css" />

  <link href="{% static 'johndyer-mediaelement-b81a0d3/mediaelementplayer.css' %}"
    rel="stylesheet" type="text/css" />

  <script
    src="{% static 'js/jquery.js' %}"
    type="text/javascript">
  </script>

  <script
    src="{% static 'johndyer-mediaelement-b81a0d3/mediaelement-and-player.min.js' %}"
    type="text/javascript">
  </script>

  <script
    src="{% static 'js/localizome.js' %}"
    type="text/javascript">
  </script>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '{{ GOOGLE_ANALYTICS_ID }}', 'auto');
    ga('send', 'pageview');
  </script>

  <title>EE Localizome</title>
</head>

website/templates/home.html
{% extends "base.html" %}

{% block content %}
  <div id="blurb" class="increase-line-height">
    The Early Embryo Localizome project examines 100 GFP-fused proteins
    in their native cellular environments during the first two rounds
    of mitotic cell division in the <i>C. elegans</i> developing embryo.
  </div>
  <div id="homepage-images">
    <a href="http://cgsb.as.nyu.edu/" target="_blank">
      <img id="cgsb-logo" src="{{ STATIC_URL }}images/cgsb-logo.png" >
    </a>
    <img id="homepage-main-image" src="{{ STATIC_URL }}images/homepage.png" >
    <a href="http://nyu.edu/" target="_blank">
      <img id="nyu-logo" src="{{ STATIC_URL }}images/nyu-logo.png" >
    </a>
  </div>

  <hr id="homepage-line"></hr>

  <div id="blurb">
    <!--
    <h3>Paper</h3>
    <a href="" target="_blank"><i>The title of the paper</i></a>,
    Miyeko Mana, ..., The Journal
    -->

    <h3 id="contact">Contact</h3>
    Corresponding author Dr. Fabio Piano: fp1 < at > nyu.edu
  </div>
{% endblock %}

website/templates/spaciotemporal_results.html
{% extends "base_matrix.html"%}


{% block page_title %}
	<h3>
		Co-expressed Proteins
		{% if compartment and timepoint %}
			in <span class="header-emphasis">{{ compartment.name }}</span> 
			at <span class="header-emphasis">{{ timepoint.get_cell_cycle_category_display }}: </span>
			<span class="header-emphasis">{{ timepoint.name }}</span>
		{% elif compartment %}
			in <span class="header-emphasis">{{ compartment.name }}</span>
		{% elif timepoint %}
			at <span class="header-emphasis">{{ timepoint.get_cell_cycle_category_display }}: {{ timepoint.name }}</span>
		{% endif %}
	</h3>
{% endblock %}


{% block prematrix %}
	<div id="below-header">
		{% if signals %}
			Showing all proteins present or weak
			{% if compartment and timepoint %}
				in this compartment and timepoint.
			{% elif compartment %}
				in this compartment.
			{% elif timepoint %}
				at this timepoint.
			{% endif %}
			
		{% else %}
			No proteins expressed
			{% if compartment and timepoint %}
				in this compartment and timepoint.
			{% elif compartment %}
				in this compartment.
			{% elif timepoint %}
				at this timepoint.
			{% endif %}

		{% endif %}
	</div>
{% endblock prematrix %}


{% block next_to_matrix %}
	{% if signals %}
		<div id="next-to-matrix" class="increase-line-height">
			{% include "matrix_key_normal.html" %}
		</div>
	{% endif %}		
{% endblock next_to_matrix %}

website/templates/spatiotemporal_results.html
{% extends "base.html"%}

{% block page_title %}
  <h3>
    Proteins Observed
    {% if compartment and timepoint %}
      in <span class="header-emphasis">{{ compartment.name }}</span>
      at <span class="header-emphasis">{{ timepoint.get_cell_cycle_category_display }}: </span>
      <span class="header-emphasis">{{ timepoint.name }}</span>
    {% elif compartment %}
      in <span class="header-emphasis">{{ compartment.name }}</span>
    {% elif timepoint %}
      at <span class="header-emphasis">{{ timepoint.get_cell_cycle_category_display }}: {{ timepoint.name }}</span>
    {% endif %}
  </h3>
{% endblock page_title %}

{% block content %}
  <div id="below-header">
    {% if signals %}
      Showing all proteins observed
      {% if compartment and timepoint %}
        in this compartment and timepoint.
      {% elif compartment %}
        in this compartment.
      {% elif timepoint %}
        at this timepoint.
      {% endif %}
    {% else %}
      No proteins observed
      {% if compartment and timepoint %}
        in this compartment and timepoint.
      {% elif compartment %}
        in this compartment.
      {% elif timepoint %}
        at this timepoint.
      {% endif %}
    {% endif %}
  </div>

  <div id="matrix-key-wrapper">
    {% if signals %}
      {% if compartment and timepoint %}
        <table id="spatiotemporal-results" class="spatiotemporal-both">
          <thead>
            <tr>
              <th class="top-row left-column"><b>Common</b></th>
              <th class="top-row"><b>Canonical</b></th>
              <th class="narrow no-background no-right-border"></th>
            </tr>
          </thead>
          {% for signal in signals %}
            <tr>
              <th class="left-column y-axis-spatiotemporal-result row-header">
                <a href="{% url 'protein_detail_url' common_name=signal.protein %}">
                  {{ signal.protein|upper }}
                </a>
              </th>
              <th class="y-axis-spatiotemporal-result row-header">
                {{ signal.protein.sequence }}
              </th>
              <td width="50" class="signal strength{{ signal.strength }}"></td>
            </tr>
          {% endfor %}
        </table>
        <table id="table-thead-fixed" class="spatiotemporal-both"></table>
      {% else %}
        <table id="spatiotemporal-results" class="matrix">
          <thead>
            {% if compartment %}
              {% include "matrix_xaxis_timepoints.html" %}
            {% elif timepoint %}
              {% include "matrix_xaxis_compartments.html" %}
            {% endif %}
          </thead>

          {% regroup signals by protein_id as proteins_signals %}

          {% for protein_signals in proteins_signals %}
            <tr>
              {% with protein_signals.list.0.protein as protein %}
                <th class="left-column y-axis-spatiotemporal-result row-header" colspan="2">
                  <a href="{% url 'protein_detail_url' common_name=protein %}">
                    {{ protein|upper }}
                  </a>
                </th>
                <th class="y-axis-spatiotemporal-result row-header">
                  {{ protein.sequence }}
                </th>
              {% endwith %}

              {% for signal in protein_signals.list %}
                <td class="signal
                  strength{{ signal.strength }}
                  {% if compartment %}
                    {% if forloop.counter == 8 or forloop.counter == 14 %}
                      bold-right
                    {% endif %}
                  {% elif timepoint %}
                    {% if forloop.counter == 4 or forloop.counter == 15 %}
                      bold-right
                    {% endif %}
                  {% endif %}
                "></td>
              {% endfor %}
            </tr>
          {% endfor %}
        </table>
        <table id="table-thead-fixed" class="matrix"></table>
      {% endif %}

      <div id="next-to-matrix" class="shaded-box">
        {% include "matrix_key_normal.html" %}
      </div>
    {% endif %}
  </div>
{% endblock content %}